
POST /household/1/movement HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "houseAddressMovement": "대구",
  "houseMovementReportDate": "2011-11-22"
}

###

PUT /household/1/movement/2011-11-22 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "houseMovementReportDate": "2222-11-22",
  "houseAddressMovement": "울산"
}

###
DELETE /household/1/movement/2222-11-22 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
