
POST /household HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "householdResidentSerialNumber": 4,
  "householdCompositionDate": "2023-11-11",
  "householdCompositionReasonCode": "세대분리",
  "currentHouseMovementAddress": "대전"
}


###



DELETE /household/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json